language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
  matrix:
  - OCAML_VERSION=4.04 PACKAGE=mirage-net-xen
  - OCAML_VERSION=4.03 PACKAGE=mirage-net-xen
